version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: logihub_db
    environment:
      MYSQL_ROOT_PASSWORD: anushka
      MYSQL_DATABASE: logihub_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - logihub_network

  backend:
    build:
      context: ./logihub
    container_name: logihub_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/logihub_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: anushka
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - mysql
    networks:
      - logihub_network

networks:
  logihub_network:

volumes:
  db_data:
