version: '3.8'

services:
  backend:
    build: ./backened
    container_name: logihub-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/logihub_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: logihub-db
    restart: always
    environment:
      MYSQL_DATABASE: logihub_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
