services:
  - type: web
    name: logihub-backend
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://logihub-db:3306/logihub
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: anushka

databases:
  - name: logihub-db
    databaseName: logihub
    user: root
